/**
 * The app's icon set: Heroicons 20px solid, chosen for the filled, compact look.
 * Names stay descriptive of their use so a swap of the underlying set is one file.
 * shadcn primitives in components/ui keep their own small chevron and check glyphs.
 */
export {
  ArrowDownTrayIcon as DownloadIcon,
  ArrowPathIcon as LoaderCircleIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon as LogOutIcon,
  BoltIcon as PlugIcon,
  CheckIcon,
  ChevronLeftIcon,
  ClockIcon as HistoryIcon,
  CodeBracketIcon as CodeIcon,
  Cog6ToothIcon as SettingsIcon,
  CreditCardIcon,
  CommandLineIcon as TerminalIcon,
  ComputerDesktopIcon as MonitorIcon,
  CpuChipIcon as BotIcon,
  DocumentArrowDownIcon as FileDownIcon,
  DocumentDuplicateIcon as CopyIcon,
  DocumentTextIcon as FileTextIcon,
  EllipsisHorizontalIcon as EllipsisIcon,
  ExclamationTriangleIcon as TriangleAlertIcon,
  EyeIcon,
  EyeSlashIcon as EyeOffIcon,
  FolderIcon,
  FolderPlusIcon,
  GlobeAltIcon as GlobeIcon,
  HomeIcon,
  KeyIcon as KeyRoundIcon,
  LightBulbIcon as BrainIcon,
  LinkIcon,
  LockClosedIcon as LockIcon,
  MagnifyingGlassIcon as SearchIcon,
  MapIcon as CompassIcon,
  MoonIcon,
  PaperAirplaneIcon as SendHorizontalIcon,
  PencilSquareIcon as PencilIcon,
  PlusIcon,
  QueueListIcon as ScrollTextIcon,
  ShareIcon as Share2Icon,
  ShieldCheckIcon,
  SparklesIcon,
  Square3Stack3DIcon as LayersIcon,
  SunIcon,
  TrashIcon as Trash2Icon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  XMarkIcon as XIcon,
} from "@heroicons/react/20/solid";

export type Icon = React.ComponentType<React.SVGProps<SVGSVGElement>>;
