/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as PIdRouteImport } from './routes/p/$id'
import { Route as RawIdRouteImport } from './routes/raw/$id'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAppConnectRouteImport } from './routes/_auth/app/connect'
import { Route as AuthAppNewRouteImport } from './routes/_auth/app/new'
import { Route as AuthInviteTokenRouteImport } from './routes/_auth/invite/$token'
import { Route as AuthOauthConsentRouteImport } from './routes/_auth/oauth/consent'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthPIdEditRouteImport } from './routes/_auth/p/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RawIdRoute = RawIdRouteImport.update({
  id: '/raw/$id',
  path: '/raw/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppConnectRoute = AuthAppConnectRouteImport.update({
  id: '/app/connect',
  path: '/app/connect',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppNewRoute = AuthAppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInviteTokenRoute = AuthInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOauthConsentRoute = AuthOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPIdEditRoute = AuthPIdEditRouteImport.update({
  id: '/p/$id/edit',
  path: '/p/$id/edit',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/login': typeof GuestLoginRoute
  '/p/$id': typeof PIdRoute
  '/raw/$id': typeof RawIdRoute
  '/app/connect': typeof AuthAppConnectRoute
  '/app/new': typeof AuthAppNewRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/p/$id/edit': typeof AuthPIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/login': typeof GuestLoginRoute
  '/p/$id': typeof PIdRoute
  '/raw/$id': typeof RawIdRoute
  '/app/connect': typeof AuthAppConnectRoute
  '/app/new': typeof AuthAppNewRoute
  '/invite/$token': typeof AuthInviteTokenRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/p/$id/edit': typeof AuthPIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/_guest/login': typeof GuestLoginRoute
  '/p/$id': typeof PIdRoute
  '/raw/$id': typeof RawIdRoute
  '/_auth/app/connect': typeof AuthAppConnectRoute
  '/_auth/app/new': typeof AuthAppNewRoute
  '/_auth/invite/$token': typeof AuthInviteTokenRoute
  '/_auth/oauth/consent': typeof AuthOauthConsentRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/p/$id/edit': typeof AuthPIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.well-known/$'
    | '/login'
    | '/p/$id'
    | '/raw/$id'
    | '/app/connect'
    | '/app/new'
    | '/invite/$token'
    | '/oauth/consent'
    | '/api/auth/$'
    | '/app/'
    | '/p/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.well-known/$'
    | '/login'
    | '/p/$id'
    | '/raw/$id'
    | '/app/connect'
    | '/app/new'
    | '/invite/$token'
    | '/oauth/consent'
    | '/api/auth/$'
    | '/app'
    | '/p/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/mcp'
    | '/.well-known/$'
    | '/_guest/login'
    | '/p/$id'
    | '/raw/$id'
    | '/_auth/app/connect'
    | '/_auth/app/new'
    | '/_auth/invite/$token'
    | '/_auth/oauth/consent'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/p/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  McpRoute: typeof McpRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  PIdRoute: typeof PIdRoute
  RawIdRoute: typeof RawIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/$id': {
      id: '/raw/$id'
      path: '/raw/$id'
      fullPath: '/raw/$id'
      preLoaderRoute: typeof RawIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/connect': {
      id: '/_auth/app/connect'
      path: '/app/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AuthAppConnectRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/new': {
      id: '/_auth/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthAppNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invite/$token': {
      id: '/_auth/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthInviteTokenRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/oauth/consent': {
      id: '/_auth/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AuthOauthConsentRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/p/$id/edit': {
      id: '/_auth/p/$id/edit'
      path: '/p/$id/edit'
      fullPath: '/p/$id/edit'
      preLoaderRoute: typeof AuthPIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppConnectRoute: typeof AuthAppConnectRoute
  AuthAppNewRoute: typeof AuthAppNewRoute
  AuthInviteTokenRoute: typeof AuthInviteTokenRoute
  AuthOauthConsentRoute: typeof AuthOauthConsentRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthPIdEditRoute: typeof AuthPIdEditRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppConnectRoute: AuthAppConnectRoute,
  AuthAppNewRoute: AuthAppNewRoute,
  AuthInviteTokenRoute: AuthInviteTokenRoute,
  AuthOauthConsentRoute: AuthOauthConsentRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthPIdEditRoute: AuthPIdEditRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  McpRoute: McpRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  PIdRoute: PIdRoute,
  RawIdRoute: RawIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
